twitter:
  card: summary_large_image
  username: bashaway
defaults:
  - scope:
      path: ""
    values:
      image: i.gyazo.com/778bae374fc41825733c6370d919884f.png
        height: 630
        width: 1200
