theme: jekyll-theme-cayman
twitter:
  username: bashaway
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/rrdcalendar_description.png
        height: 630
        width: 1200

