twitter:
  card: summary_large_image
  username: bashaway
defaults:
  - scope:
      path: ""
    values:
      image: 
        src: https://i.gyazo.com/dcbb19d5464fa755d42b5c62df6c1b81.png
        height: 630
        width: 1200
